### ISSUE TITLE
API for StringArray, IntArray, FloatArray, BoolArray

### ISSUE THREAD

**Issue by Isaaclbj** [newmannj/CS4500A1P2#2]
It is strongly implied that we use different APIs for each of these primitive types. Can you make APIs for them, please

**Comment by newmannj** [comment]
See requested changes on PR. We are also willing to add the API ourselves and then have you request changes if needed, or we can iterate on your implementation. Whatever works best for you.

**Comment by newmannj** [comment]
We have added classes for Int, Float and Bool arrays, as well as update our object.h and string.h to be the ones proposed by chasebish. Tests for Int, Float and Bool arrays to be added sometime today.
